services:
  api:
    image: ${IMAGE_NAME:-node-api}
    build:
      context: .
      args:
        NODE_ENV: ${NODE_ENV}
        IMAGE_NAME: ${IMAGE_NAME}
    container_name: ${CONTAINER_NAME:-node-api-cicd}
    ports:
      - "${PORT:-5000}:${PORT:-5000}"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=${PORT:-5000}
    #volumes:
    # - .:/app
    command: ${START_CMD:-npm run dev}
    restart: unless-stopped