name: publish

on:
  push:
    branches: ['main']
  

jobs:
  create-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN_ACTIONS }}

      - name: Build Image
        run: |
          docker build . --tag ghcr.io/gusdellac/node-api-cicd:latest
          docker push ghcr.io/gusdellac/node-api-cicd